# Generated by Django 3.2 on 2022-06-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220627_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='secondary_color',
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[(1, 'Silk'), (2, 'Velvet'), (3, 'Satin')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[(1, 'Default'), (2, 'Camo'), (3, 'Bandana')], default=1, max_length=200),
        ),
    ]
