# Generated by Django 3.2 on 2022-06-24 19:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('secondary_color', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
