# Generated by Django 3.2 on 2022-06-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220627_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('Silk', 'Silk'), ('Velvet', 'Velvet'), ('Satin', 'Satin')], default='Silk', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('Default', 'Default'), ('Camo', 'Camo'), ('Bandana', 'Bandana')], default='Default', max_length=200),
        ),
    ]
